SET TIME ZONE 'UTC';

BEGIN;

CREATE TABLE users (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
    entries INT DEFAULT 0,
    password TEXT NOT NULL,
	joined TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



COMMIT;
